#################################################
# Docker install
#################################################
---

- name: Uninstall old versions
  apt: name={{ item }} state=absent update_cache=yes purge=yes
  loop: [ 'docker', 'docker-engine', 'docker.io', 'containerd', 'runc',]

- name: Install prereq
  apt: name={{ item }} state=present update_cache=yes
  loop: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    state: present

- name: Install Docker
  apt: name={{ item }} state=present update_cache=yes
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']