apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: staticpod
spec:
  hostNetwork: true
  containers:
    - name: grafana
      image: grafana/grafana-oss
      volumeMounts: 
      - mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
        name: grafana-datasource-file
      ports:
        - name: graf
          containerPort: 80
          protocol: TCP
  volumes:
    - name: grafana-datasource-file
      hostPath:
        path: /tmp/test_task/files/grafana-datasource.yml
        type: FileOrCreate